image: python:3.9  # Usa una imagen de Python compatible

stages:
  - test

before_script:
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .  # Esta línea es crucial para instalar tu paquete

test:
  stage: test
  script:
    - pytest tests/ --verbose --junitxml=report.xml  # Ejecuta las pruebas con pytest
  
  artifacts:
    reports:
      junit: report.xml  # Guarda el reporte de pruebas en GitLab
  only:
    - main
    - dev
