image: python:3.9  # Usa una imagen de Python compatible

stages:
  - test

before_script:
  # Instalar dependencias de sistema para OpenCV
  - apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
  # Configuración del entorno Python
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .

test:
  stage: test
  script:
    - pytest tests/ --verbose --junitxml=report.xml
  
  artifacts:
    reports:
      junit: report.xml
  only:
    - main
    - dev
